using System;
using System.Collections.Generic;

namespace IfredrixDownloadManager;

/// <summary>
/// Indonesian/English UI strings. English is the fallback for missing keys.
/// Switch via <see cref="SetLang"/> ("id"/"en"); dialogs read on open, the
/// main window re-applies immediately through ApplyLanguage.
/// </summary>
public static class Localization
{
    public static string Lang { get; private set; } = "id";

    public static void SetLang(string? lang)
    {
        Lang = string.Equals(lang, "en", StringComparison.OrdinalIgnoreCase) ? "en" : "id";
    }

    public static string T(string key)
    {
        var table = Lang == "en" ? En : Id;
        if (table.TryGetValue(key, out var value)) return value;
        if (En.TryGetValue(key, out var fallback)) return fallback;
        return key;
    }

    private static readonly Dictionary<string, string> En = new()
    {
        // Menus
        ["menu.file"] = "&File",
        ["menu.downloads"] = "&Downloads",
        ["menu.view"] = "&View",
        ["menu.tools"] = "&Tools",
        ["menu.help"] = "&Help",
        ["menu.addUrl"] = "Add &URL",
        ["menu.addBatch"] = "Add &Batch...",
        ["menu.exportQueue"] = "E&xport queue...",
        ["menu.importQueue"] = "I&mport queue...",
        ["menu.addTorrent"] = "Add &Torrent...",
        ["menu.grabLinks"] = "&Grab Links",
        ["menu.exit"] = "E&xit",
        ["menu.start"] = "&Start",
        ["menu.pause"] = "&Pause",
        ["menu.resume"] = "&Resume",
        ["menu.cancel"] = "&Cancel",
        ["menu.remove"] = "Re&move",
        ["menu.progress"] = "&Progress...",
        ["menu.torRoute"] = "Route via &Tor",
        ["status.torOn"] = "Tor routing ON: {0}",
        ["status.torOff"] = "Tor routing OFF (direct): {0}",
        ["menu.refresh"] = "Refresh A&ddress",
        ["menu.limit"] = "Speed &limit...",
        ["menu.openFolder"] = "&Open Folder",
        ["menu.copyUrl"] = "Copy &URL",
        ["menu.properties"] = "P&roperties",
        ["menu.skinLight"] = "Skin: &Light",
        ["menu.skinDark"] = "Skin: &Dark",
        ["menu.langId"] = "Indonesia",
        ["menu.langEn"] = "English",
        ["menu.language"] = "&Language",
        ["menu.customToolbar"] = "&Customize Toolbar...",
        ["menu.browsers"] = "&Browsers...",
        ["menu.resetColumns"] = "&Reset Columns",
        ["menu.streamUrl"] = "&Stream URL...",
        ["menu.torSetup"] = "&Tor Setup...",
        ["menu.proxy"] = "&Proxy...",
        ["menu.catFolders"] = "Category &Folders...",
        ["menu.exclusions"] = "URL E&xclusions...",
        ["menu.assoc"] = "Associate .torrent files",
        ["menu.checksum"] = "Verify checks&um...",
        // Checksum
        ["hash.title"] = "Verify checksum",
        ["hash.algo"] = "Algorithm",
        ["hash.compute"] = "Compute",
        ["hash.expected"] = "Expected",
        ["hash.actual"] = "Actual",
        ["hash.verify"] = "Verify",
        ["hash.computeFirst"] = "Compute the hash first.",
        ["hash.match"] = "MATCH ({0}).",
        ["hash.mismatch"] = "MISMATCH - the file differs.",
        ["hash.needFile"] = "Checksum needs a finished download with its file on disk.",
        ["menu.siteLogins"] = "Site &logins...",
        // Site logins
        ["login.title"] = "Site logins",
        ["login.hint"] = "Saved credentials per host, sent automatically as Basic auth.",
        ["login.host"] = "Host",
        ["login.user"] = "Username",
        ["login.pass"] = "Password",
        ["login.addUpdate"] = "Add / Update",
        ["login.needBoth"] = "Enter a host and a username.",
        ["status.assocOn"] = ".torrent files open with this app.",
        ["status.assocOff"] = ".torrent association removed.",
        ["menu.settings"] = "&Settings...",
        ["menu.about"] = "&About",
        ["menu.updates"] = "Check for &updates...",
        // Buttons
        ["btn.addUrl"] = "Add URL",
        ["btn.addTorrent"] = "Add Torrent",
        ["btn.stream"] = "Stream URL",
        ["btn.grabLinks"] = "Grab Links",
        ["btn.browsers"] = "Browsers",
        ["btn.settings"] = "Settings",
        ["btn.start"] = "Start",
        ["btn.pause"] = "Pause",
        ["btn.resume"] = "Resume",
        ["btn.cancel"] = "Cancel",
        ["btn.remove"] = "Remove",
        ["btn.openFolder"] = "Open Folder",
        // Labels
        ["lbl.search"] = "Search:",
        ["lbl.category"] = "Category:",
        ["lbl.ready"] = "Ready",
        ["lbl.tray"] = "ifredrix Download Manager",
        ["tip.close"] = "Close",
        ["tip.min"] = "Minimize",
        ["tip.max"] = "Maximize / Restore",
        // Grid columns
        ["col.filename"] = "File Name",
        ["col.size"] = "Size",
        ["col.progress"] = "Progress",
        ["col.speed"] = "Speed",
        ["col.eta"] = "ETA",
        ["col.status"] = "Status",
        ["col.type"] = "Type",
        ["col.category"] = "Category",
        // Header column menu
        ["hdr.moveLeft"] = "Move '{0}' left",
        ["hdr.moveRight"] = "Move '{0}' right",
        ["hdr.reset"] = "Reset columns",
        // Row menu
        ["row.refresh"] = "Refresh address",
        ["row.properties"] = "Properties",
        ["row.copyUrl"] = "Copy URL",
        ["row.openFolder"] = "Open folder",
        // Task display values
        ["st.Pending"] = "Pending",
        ["st.Queued"] = "Queued",
        ["st.Downloading"] = "Downloading",
        ["st.Paused"] = "Paused",
        ["st.Completed"] = "Completed",
        ["st.Error"] = "Error",
        ["st.Cancelled"] = "Cancelled",
        ["ty.Regular"] = "Regular",
        ["ty.Torrent"] = "Torrent",
        ["ty.Stream"] = "Stream",
        ["cat.All"] = "All",
        ["cat.Video"] = "Video",
        ["cat.Audio"] = "Audio",
        ["cat.Archive"] = "Archive",
        ["cat.Document"] = "Document",
        ["cat.Application"] = "Application",
        ["cat.Image"] = "Image",
        ["cat.Torrent"] = "Torrent",
        ["cat.Streams"] = "Streams",
        ["cat.Other"] = "Other",
        // Status line
        ["status.pasteLink"] = "Paste a link first.",
        ["status.addCancelled"] = "Download cancelled.",
        ["status.badScheme"] = "Only http://, https://, ftp://, ftps://, mms://, magnet:, or a local .torrent path are supported here.",
        ["status.contacting"] = "Contacting source...",
        ["status.queued"] = "Queued: {0}",
        ["status.queuedTor"] = "Queued via Tor: {0}",
        ["status.queuedStream"] = "Queued stream: {0}",
        ["status.queuingStream"] = "Queuing stream...",
        ["status.fetchYtdlp"] = "Fetching yt-dlp (first run, one-time)...",
        ["status.fetchYtdlpPct"] = "Fetching yt-dlp... {0:F0}%",
        ["status.torrentFile"] = "Downloading .torrent file...",
        ["status.failed"] = "Failed: {0}",
        ["status.finished"] = "Finished: {0}",
        ["notify.finished"] = "Download finished",
        ["status.failedTask"] = "Failed: {0} ({1})",
        ["status.streamClipboard"] = "Stream link detected on clipboard - paste it in the URL box or press Stream.",
        ["status.clipboardFound"] = "{0} link(s) found on the clipboard - adding.",
        ["status.streamUrlFirst"] = "Paste a stream URL first.",
        ["status.schedStart"] = "Scheduler: queue started at {0:HH:mm}.",
        ["status.schedStop"] = "Scheduler: all downloads paused at {0:HH:mm}.",
        ["status.settingsSaved"] = "Settings saved.",
        ["status.torReady"] = "Tor ready at {0}:{1}.",
        ["status.torFailed"] = "Tor failed: {0}",
        ["status.torNotFound"] = "Tor: tor.exe not found. Open Settings -> Tor setup.",
        ["status.refreshing"] = "Refreshing address...",
        ["status.refreshed"] = "Address refreshed. {0}",
        ["status.refreshFailed"] = "Refresh failed: {0}",
        ["status.limitSet"] = "Speed limit for {0}: {1} KB/s.",
        ["status.limitGlobal"] = "Speed limit for {0}: global.",
        ["status.captureOk"] = "Browser capture listening on 127.0.0.1:{0}",
        ["status.captureFail"] = "Browser capture failed to start (port in use)",
        ["status.catSaved"] = "Category folders saved.",
        ["status.exSaved"] = "URL exclusions saved.",
        ["status.exported"] = "Queue exported: {0}",
        ["status.exportFailed"] = "Export failed: {0}",
        ["status.imported"] = "Queue imported: {0} new download(s).",
        ["status.importFailed"] = "Import failed: {0}",
        ["status.proxySaved"] = "Proxy settings saved.",
        ["status.loginSaved"] = "Site logins saved.",
        ["status.doneAll"] = "All downloads finished",
        ["status.doneShutdownIn"] = "Shutdown in 60 seconds.",
        ["status.doneShutdownAbort"] = " (run 'shutdown /a' to abort).",
        ["status.doneHibernate"] = "Hibernating.",
        ["status.doneSleep"] = "Sleeping.",
        ["status.doneFailed"] = "After-done action failed: {0}",
        ["bar.speed"] = "{0} down | {1} up",
        ["bar.active"] = "Active: {0} | Queued: {1}",
        ["bar.counts"] = "Downloads: {0}   Completed: {1}",
        ["notify.capture"] = "Browser capture",
        ["notify.captured"] = "Captured from {0}: {1}",
        // Dialogs: generic
        ["dlg.ok"] = "OK",
        ["dlg.cancel"] = "Cancel",
        ["dlg.close"] = "Close",
        ["dlg.save"] = "Save",
        ["dlg.browse"] = "Browse",
        ["dlg.reset"] = "Reset",
        // Message boxes
        ["msg.addTitle"] = "Could not add download",
        ["msg.streamTitle"] = "Could not add stream",
        ["msg.torrentTitle"] = "Could not add torrent link",
        ["msg.streamHostTitle"] = "Stream URL",
        ["msg.streamHostBody"] = "This URL is not in the list of known streaming hosts. Open the stream dialog anyway?",
        ["msg.settingsTitle"] = "Settings",
        ["msg.noFolder"] = "Please choose a download folder.",
        ["msg.badFolder"] = "That folder cannot be used:\n{0}",
        ["msg.startupFail"] = "Could not update startup entry:\n{0}",
        ["msg.browserFailTitle"] = "Browser integration",
        ["msg.browserFail"] = "Could not open {0}:\n{1}",
        ["msg.aboutTitle"] = "About",
        ["msg.notInstalled"] = "not installed",
        // Self-update
        ["upd.title"] = "Check for updates",
        ["upd.url"] = "Update manifest URL (generic JSON or GitHub Releases API)",
        ["upd.check"] = "Check",
        ["upd.checking"] = "Checking...",
        ["upd.current"] = "Current version: {0}",
        ["upd.available"] = "Version {0} available (current {1}).",
        ["upd.latest"] = "You already have the latest version ({0}).",
        ["upd.hint"] = "Example: https://raw.githubusercontent.com/ifredrix/DownloadManager/main/update/latest.json",
        ["upd.downloadRun"] = "Download & Run",
        ["upd.saved"] = "Saved: {0}",
        ["upd.runNow"] = "Update downloaded. Run it now? (The app will exit.)\n{0}",
        // Settings dialog
        ["set.title"] = "Settings",
        ["set.folder"] = "Download folder",
        ["set.concurrent"] = "Simultaneous downloads",
        ["set.connections"] = "Connections per download",
        ["set.speed"] = "Speed limit (KB/s)",
        ["set.speedHint"] = "0 = no limit",
        ["set.clipboard"] = "Watch clipboard and add links automatically",
        ["set.autostartDl"] = "Start downloads at once",
        ["set.notify"] = "Notify me when a download finishes",
        ["set.schedStart"] = "Start queued at",
        ["set.schedStop"] = "Pause all at",
        ["set.afterDone"] = "When all downloads finish",
        ["set.skin"] = "Skin",
        ["set.accent"] = "Accent",
        ["set.customToolbar"] = "Customize toolbar...",
        ["set.routeTor"] = "Route all via Tor",
        ["set.torSetup"] = "Tor setup...",
        ["set.startWindows"] = "Start with Windows",
        ["set.confirmDl"] = "Confirm downloads",
        ["set.none"] = "None",
        ["set.shutdown"] = "Shutdown",
        ["set.sleep"] = "Sleep",
        ["set.hibernate"] = "Hibernate",
        // Grab / spider
        ["grab.title"] = "Links found on the clipboard",
        ["grab.hint"] = "Tick the links you want to download:",
        ["grab.selectNone"] = "Select none",
        ["grab.selectAll"] = "Select all",
        ["grab.download"] = "Download",
        ["spider.title"] = "Grab links from page",
        ["spider.fetch"] = "Fetch",
        ["spider.depth0"] = "This page only",
        ["spider.depth1"] = "This page + 1 level (same site)",
        ["spider.filesOnly"] = "Files only (skip page links)",
        ["spider.idle"] = "Idle",
        ["spider.needUrl"] = "Enter a page address first.",
        ["spider.fetching"] = "Fetching...",
        ["spider.cancelled"] = "Cancelled.",
        // Stream dialog
        ["stream.title"] = "Capture stream (yt-dlp)",
        ["stream.list"] = "List formats",
        ["stream.download"] = "Download",
        ["stream.openFolder"] = "Open folder",
        ["stream.getTool"] = "Get yt-dlp",
        ["stream.detecting"] = "yt-dlp: detecting...",
        ["stream.notFound"] = "yt-dlp: not found - press Get yt-dlp to fetch it automatically",
        ["stream.enumerating"] = "Enumerating formats...",
        ["stream.starting"] = "Starting yt-dlp...",
        ["stream.fetching"] = "Downloading yt-dlp... {0:F0}%",
        ["stream.toolReady"] = "yt-dlp ready.",
        ["stream.checkFfmpeg"] = "Checking ffmpeg (merges / TS remux)...",
        // Tor dialog
        ["tor.title"] = "Tor settings",
        ["tor.mode"] = "Tor connection",
        ["tor.off"] = "Off - no Tor",
        ["tor.external"] = "External - use running Tor",
        ["tor.managed"] = "Built-in tor - run by ifredrix",
        ["tor.endpoint"] = "SOCKS host:port",
        ["tor.exe"] = "tor.exe (built-in)",
        ["tor.exePlaceholder"] = "(empty = use the app's bundled Tor)",
        ["tor.find"] = "Find",
        ["tor.routeAll"] = "Route all HTTP downloads via Tor",
        ["tor.hint"] = ".onion addresses always use Tor when a connection is available.\r\nTor Browser = port 9150 when open; expert bundle = 9050.",
        ["tor.test"] = "Test",
        ["tor.notFound"] = "Status: tor.exe not found.",
        ["tor.exeFound"] = "Status: tor.exe found.",
        ["tor.checking"] = "Status: checking torproject.org...",
        ["tor.startingPct"] = "Status: starting Tor... {0}% - circuits are not ready yet.",
        ["tor.checkingCircuit"] = "Status: {0}:{1} answers, proving a real Tor circuit...",
        ["tor.noCircuit"] = "Status: {0}:{1} answers but has no usable Tor circuit yet (still bootstrapping). Retry shortly.",
        ["tor.torReady"] = "Status: connected to the Tor network (exit {0}) - ready to download via Tor.",
        ["tor.noUpdate"] = "Status: bundled Tor v{0} is already the latest.",
        ["tor.updateAvail"] = "Status: v{0} installed, v{1} available (SHA256-verified). Press Download.",
        ["tor.updateAvailNew"] = "Status: v{0} available (SHA256-verified, official site only).",
        ["tor.downloading"] = "Status: downloading Tor... {0:F0}%",
        ["tor.installed"] = "Status: installed -> {0}",
        ["tor.externalKeepsRunning"] = "Bundle ready - External mode keeps using the already-running Tor. Switch to Managed + OK to run this build.",
        ["tor.checkUpdate"] = "Check for update",
        ["tor.download"] = "Download & install v{0}",
        ["tor.bundledNone"] = "Bundled Tor: none (uses Tor Browser copy or PATH)",
        ["tor.bundledUnknown"] = "Bundled Tor: unknown",
        ["tor.reachable"] = "Status: Tor reachable at {0}:{1}.",
        ["tor.unreachable"] = "Status: nothing listening at {0}:{1}.",
        ["tor.off"] = "Tor off",
        ["tor.tipOff"] = "Tor is disabled (Tor setup in Settings)",
        ["tor.tipBoot"] = "Tor is bootstrapping...",
        ["tor.tipOk"] = "Tor reachable at {0}:{1}",
        ["tor.tipMissing"] = "Tor not detected - .onion downloads need Tor Browser or the expert bundle",
        // Proxy dialog
        ["proxy.title"] = "Proxy settings",
        ["proxy.mode"] = "Proxy mode",
        ["proxy.host"] = "Host : port",
        ["proxy.user"] = "Username",
        ["proxy.pass"] = "Password",
        ["proxy.hint"] = "Site logins: put them in the link itself,\r\nhttp://user:pass@host/file (sent as Basic auth).",
        ["proxy.test"] = "Test",
        ["proxy.nothing"] = "Status: nothing to test for mode {0}.",
        ["proxy.reachable"] = "Status: proxy reachable.",
        ["proxy.unreachable"] = "Status: cannot reach proxy.",
        // Toolbar editor
        ["tb.title"] = "Customize toolbar",
        ["tb.hint"] = "Tick buttons to show, drag order with Up / Down:",
        ["tb.up"] = "Up",
        ["tb.down"] = "Down",
        // Browser integration
        ["br.title"] = "Browser integration",
        ["br.hint"] = "Install the extension in each browser you use. Browsers share the same capture server, no restart needed.",
        ["br.installed"] = "installed",
        ["br.notFound"] = "not found",
        ["br.connected"] = "connected ✓",
        ["br.notSeen"] = "not seen ✗",
        ["br.install"] = "Install...",
        ["br.steps"] = "Extension folder copied to the clipboard.\n\n{0}",
        ["br.stepsFx"] = "1. The Firefox debugging page opens.\n2. Click \"Load Temporary Add-on…\".\n3. Pick manifest.json inside this folder (already copied):\n{0}",
        ["br.stepsCr"] = "1. The extensions page opens. Turn on Developer mode.\n2. Click \"Load unpacked\".\n3. Select this folder (already copied):\n{0}",
        // Category folders
        ["cf.title"] = "Category folders",
        ["cf.hint"] = "Where each kind of download is saved. Empty = main download folder.",
        ["cf.category"] = "Category",
        ["cf.folder"] = "Folder",
        ["cf.main"] = "(main folder)",
        ["cf.clear"] = "Clear",
        ["cf.resetAll"] = "Reset all",
        // Speed limit
        ["sl.hint"] = "0 = use the global limit.",
        ["sl.limitTo"] = "Limit this download to (KB/s):",
        ["sl.title"] = "Speed limit",
        // Batch add
        ["batch.title"] = "Add batch",
        ["batch.hint"] = "One link per line (or .torrent paths). Each is routed automatically.",
        ["batch.add"] = "Add all",
        ["batch.found"] = "{0} link(s) found.",
        ["batch.done"] = "{0} link(s) sent to queue.",
        // URL exclusions
        ["ex.title"] = "URL exclusions",
        ["ex.hint"] = "One wildcard pattern per line (* and ?). # starts a comment.\r\nMatched links are skipped by clipboard and browser capture.",
        ["ex.test"] = "Test URL:",
        ["ex.check"] = "Check",
        ["ex.excluded"] = "Excluded (will be skipped).",
        ["ex.allowed"] = "Allowed (will be captured).",
        // Properties
        ["pr.title"] = "Download properties",
        ["pr.file"] = "File name",
        ["pr.url"] = "URL",
        ["pr.saveAs"] = "Save as",
        ["pr.type"] = "Type",
        ["pr.category"] = "Category",
        ["pr.status"] = "Status",
        ["pr.size"] = "Size",
        ["pr.downloaded"] = "Downloaded",
        ["pr.speed"] = "Speed",
        ["pr.limit"] = "Speed limit",
        ["pr.eta"] = "ETA",
        ["pr.created"] = "Created",
        ["pr.completed"] = "Completed",
        ["pr.tor"] = "Via Tor",
        ["pr.resume"] = "Resume support",
        ["pr.error"] = "Error",
        ["pr.copyUrl"] = "Copy URL",
        ["pr.yes"] = "Yes",
        ["pr.no"] = "No",
        ["pr.none"] = "-",
        ["pr.unknown"] = "Unknown",
        ["pr.downUp"] = "{0} down / {1} up",
        ["pr.of"] = "{0} of {1} ({2:0.0}%)",
        ["pr.limitThis"] = "{0:F0} KB/s (this download)",
        ["pr.limitGlobal"] = "Global",
        // New download dialog
        ["dl.title"] = "New download",
        ["dl.url"] = "Address (URL)",
        ["dl.file"] = "File name",
        ["dl.saveIn"] = "Save in",
        ["dl.info"] = "Size: {0}   Resume: {1}",
        ["dl.needName"] = "Please enter a file name.",
        // Progress window
        ["prog.statusTab"] = "Download status",
        ["prog.speedTab"] = "Speed limiter",
        ["prog.optionsTab"] = "Options on completion",
        ["prog.status"] = "Status:",
        ["prog.size"] = "File size",
        ["prog.downloaded"] = "Downloaded",
        ["prog.rate"] = "Transfer rate",
        ["prog.eta"] = "Time remaining",
        ["prog.resume"] = "Resume capability",
        ["prog.hide"] = "<< Hide details",
        ["prog.show"] = "Show details >>",
        ["prog.pause"] = "Pause",
        ["prog.resume"] = "Resume",
        ["prog.cancel"] = "Cancel",
        ["prog.progress"] = "Progress",
        ["prog.detailCaption"] = "Start position and download progress by connection",
        ["prog.colN"] = "N.",
        ["prog.colDownloaded"] = "Downloaded",
        ["prog.colInfo"] = "Info",
        ["prog.receiving"] = "Receiving data...",
        ["prog.done"] = "Done",
        ["prog.waiting"] = "Waiting",
        ["prog.torrentConn"] = "{0} connections",
        ["prog.limitLabel"] = "Limit this download to (KB/s):",
        ["prog.limitCurrent"] = "Active limit: {0}",
        ["prog.apply"] = "Apply",
        ["prog.closeOnDone"] = "Close this window when done",
        ["prog.openFolderOnDone"] = "Open the file folder when done",
    };

    private static readonly Dictionary<string, string> Id = new()
    {
        // Menus
        ["menu.file"] = "&Berkas",
        ["menu.downloads"] = "&Unduhan",
        ["menu.view"] = "&Tampil",
        ["menu.tools"] = "&Peralatan",
        ["menu.help"] = "&Bantuan",
        ["menu.addUrl"] = "Tambah &URL",
        ["menu.addBatch"] = "Tambah &Batch...",
        ["menu.exportQueue"] = "E&kspor antrean...",
        ["menu.importQueue"] = "I&mpor antrean...",
        ["menu.addTorrent"] = "Tambah &Torrent...",
        ["menu.grabLinks"] = "Ambil &Tautan",
        ["menu.exit"] = "&Keluar",
        ["menu.start"] = "&Mulai",
        ["menu.pause"] = "&Jeda",
        ["menu.resume"] = "&Lanjutkan",
        ["menu.cancel"] = "&Batal",
        ["menu.remove"] = "&Hapus",
        ["menu.progress"] = "&Progres...",
        ["menu.torRoute"] = "Lewatkan via &Tor",
        ["status.torOn"] = "Routing Tor AKTIF: {0}",
        ["status.torOff"] = "Routing Tor MATI (langsung): {0}",
        ["menu.refresh"] = "Segarkan Alamat",
        ["menu.limit"] = "Batas &kecepatan...",
        ["menu.openFolder"] = "Buka &Folder",
        ["menu.copyUrl"] = "&Salin URL",
        ["menu.properties"] = "P&roperti",
        ["menu.skinLight"] = "Skin: &Terang",
        ["menu.skinDark"] = "Skin: &Gelap",
        ["menu.langId"] = "Indonesia",
        ["menu.langEn"] = "English",
        ["menu.language"] = "&Bahasa",
        ["menu.customToolbar"] = "&Kustomisasi Toolbar...",
        ["menu.browsers"] = "&Browser...",
        ["menu.resetColumns"] = "&Reset Kolom",
        ["menu.streamUrl"] = "&Stream URL...",
        ["menu.torSetup"] = "Setelan &Tor...",
        ["menu.proxy"] = "&Proksi...",
        ["menu.catFolders"] = "&Folder Kategori...",
        ["menu.exclusions"] = "Pengecualian &URL...",
        ["menu.assoc"] = "Asosiasikan berkas .torrent",
        ["menu.checksum"] = "Verifikasi check&sum...",
        // Checksum
        ["hash.title"] = "Verifikasi checksum",
        ["hash.algo"] = "Algoritma",
        ["hash.compute"] = "Hitung",
        ["hash.expected"] = "Ekspektasi",
        ["hash.actual"] = "Aktual",
        ["hash.verify"] = "Verifikasi",
        ["hash.computeFirst"] = "Hitung hash dulu.",
        ["hash.match"] = "COCOK ({0}).",
        ["hash.mismatch"] = "TIDAK COCOK - berkas berbeda.",
        ["hash.needFile"] = "Checksum butuh unduhan selesai yang berkasnya ada.",
        ["menu.siteLogins"] = "&Login situs...",
        // Site logins
        ["login.title"] = "Login situs",
        ["login.hint"] = "Kredensial tersimpan per host, dikirim otomatis sebagai Basic auth.",
        ["login.host"] = "Host",
        ["login.user"] = "Nama pengguna",
        ["login.pass"] = "Kata sandi",
        ["login.addUpdate"] = "Tambah / Ubah",
        ["login.needBoth"] = "Isi host dan nama pengguna.",
        ["status.assocOn"] = "Berkas .torrent dibuka dengan app ini.",
        ["status.assocOff"] = "Asosiasi .torrent dihapus.",
        ["menu.settings"] = "&Pengaturan...",
        ["menu.about"] = "&Tentang",
        ["menu.updates"] = "Cek pem&baruan...",
        // Buttons
        ["btn.addUrl"] = "Tambah URL",
        ["btn.addTorrent"] = "Tambah Torrent",
        ["btn.stream"] = "Stream URL",
        ["btn.grabLinks"] = "Ambil Tautan",
        ["btn.browsers"] = "Browser",
        ["btn.settings"] = "Pengaturan",
        ["btn.start"] = "Mulai",
        ["btn.pause"] = "Jeda",
        ["btn.resume"] = "Lanjutkan",
        ["btn.cancel"] = "Batal",
        ["btn.remove"] = "Hapus",
        ["btn.openFolder"] = "Buka Folder",
        // Labels
        ["lbl.search"] = "Cari:",
        ["lbl.category"] = "Kategori:",
        ["lbl.ready"] = "Siap",
        ["lbl.tray"] = "ifredrix Download Manager",
        ["tip.close"] = "Tutup",
        ["tip.min"] = "Kecilkan",
        ["tip.max"] = "Besarkan / Pulihkan",
        // Grid columns
        ["col.filename"] = "Nama Berkas",
        ["col.size"] = "Ukuran",
        ["col.progress"] = "Progres",
        ["col.speed"] = "Kecepatan",
        ["col.eta"] = "ETA",
        ["col.status"] = "Status",
        ["col.type"] = "Jenis",
        ["col.category"] = "Kategori",
        // Header column menu
        ["hdr.moveLeft"] = "Geser '{0}' ke kiri",
        ["hdr.moveRight"] = "Geser '{0}' ke kanan",
        ["hdr.reset"] = "Reset kolom",
        // Row menu
        ["row.refresh"] = "Segarkan alamat",
        ["row.properties"] = "Properti",
        ["row.copyUrl"] = "Salin URL",
        ["row.openFolder"] = "Buka folder",
        // Task display values
        ["st.Pending"] = "Menunggu",
        ["st.Queued"] = "Antre",
        ["st.Downloading"] = "Mengunduh",
        ["st.Paused"] = "Jeda",
        ["st.Completed"] = "Selesai",
        ["st.Error"] = "Gagal",
        ["st.Cancelled"] = "Batal",
        ["ty.Regular"] = "Reguler",
        ["ty.Torrent"] = "Torrent",
        ["ty.Stream"] = "Stream",
        ["cat.All"] = "Semua",
        ["cat.Video"] = "Video",
        ["cat.Audio"] = "Audio",
        ["cat.Archive"] = "Arsip",
        ["cat.Document"] = "Dokumen",
        ["cat.Application"] = "Aplikasi",
        ["cat.Image"] = "Gambar",
        ["cat.Torrent"] = "Torrent",
        ["cat.Streams"] = "Stream",
        ["cat.Other"] = "Lainnya",
        // Status line
        ["status.pasteLink"] = "Tempel tautan dulu.",
        ["status.addCancelled"] = "Unduhan dibatalkan.",
        ["status.badScheme"] = "Hanya http://, https://, ftp://, ftps://, mms://, magnet:, atau path .torrent lokal yang didukung.",
        ["status.contacting"] = "Menghubungi sumber...",
        ["status.queued"] = "Diantre: {0}",
        ["status.queuedTor"] = "Diantre via Tor: {0}",
        ["status.queuedStream"] = "Stream diantre: {0}",
        ["status.queuingStream"] = "Mengantre stream...",
        ["status.fetchYtdlp"] = "Mengambil yt-dlp (sekali saja)...",
        ["status.fetchYtdlpPct"] = "Mengambil yt-dlp... {0:F0}%",
        ["status.torrentFile"] = "Mengunduh berkas .torrent...",
        ["status.failed"] = "Gagal: {0}",
        ["status.finished"] = "Selesai: {0}",
        ["notify.finished"] = "Unduhan selesai",
        ["status.failedTask"] = "Gagal: {0} ({1})",
        ["status.streamClipboard"] = "Tautan stream terdeteksi di clipboard - tempel di kotak URL atau tekan Stream.",
        ["status.clipboardFound"] = "{0} tautan ditemukan di clipboard - menambahkan.",
        ["status.streamUrlFirst"] = "Tempel URL stream dulu.",
        ["status.schedStart"] = "Penjadwal: antrean dimulai {0:HH:mm}.",
        ["status.schedStop"] = "Penjadwal: semua unduhan dijeda {0:HH:mm}.",
        ["status.settingsSaved"] = "Pengaturan disimpan.",
        ["status.torReady"] = "Tor siap di {0}:{1}.",
        ["status.torFailed"] = "Tor gagal: {0}",
        ["status.torNotFound"] = "Tor: tor.exe tidak ditemukan. Buka Pengaturan -> Setelan Tor.",
        ["status.refreshing"] = "Menyegarkan alamat...",
        ["status.refreshed"] = "Alamat disegarkan. {0}",
        ["status.refreshFailed"] = "Segarkan gagal: {0}",
        ["status.limitSet"] = "Batas kecepatan {0}: {1} KB/s.",
        ["status.limitGlobal"] = "Batas kecepatan {0}: global.",
        ["status.captureOk"] = "Browser capture aktif di 127.0.0.1:{0}",
        ["status.captureFail"] = "Browser capture gagal jalan (port dipakai)",
        ["status.catSaved"] = "Folder kategori disimpan.",
        ["status.exSaved"] = "Pengecualian URL disimpan.",
        ["status.exported"] = "Antrean diekspor: {0}",
        ["status.exportFailed"] = "Ekspor gagal: {0}",
        ["status.imported"] = "Antrean diimpor: {0} unduhan baru.",
        ["status.importFailed"] = "Impor gagal: {0}",
        ["status.proxySaved"] = "Setelan proksi disimpan.",
        ["status.loginSaved"] = "Login situs disimpan.",
        ["status.doneAll"] = "Semua unduhan selesai",
        ["status.doneShutdownIn"] = "Matikan dalam 60 detik.",
        ["status.doneShutdownAbort"] = " (jalankan 'shutdown /a' untuk batalkan).",
        ["status.doneHibernate"] = "Hibernasi.",
        ["status.doneSleep"] = "Tidur.",
        ["status.doneFailed"] = "Aksi selesai gagal: {0}",
        ["bar.speed"] = "{0} unduh | {1} unggah",
        ["bar.active"] = "Aktif: {0} | Antre: {1}",
        ["bar.counts"] = "Unduhan: {0}   Selesai: {1}",
        ["notify.capture"] = "Tangkapan browser",
        ["notify.captured"] = "Ditangkap dari {0}: {1}",
        // Dialogs: generic
        ["dlg.ok"] = "OK",
        ["dlg.cancel"] = "Batal",
        ["dlg.close"] = "Tutup",
        ["dlg.save"] = "Simpan",
        ["dlg.browse"] = "Telusuri",
        ["dlg.reset"] = "Reset",
        // Message boxes
        ["msg.addTitle"] = "Tidak bisa menambah unduhan",
        ["msg.streamTitle"] = "Tidak bisa menambah stream",
        ["msg.torrentTitle"] = "Tidak bisa menambah tautan torrent",
        ["msg.streamHostTitle"] = "Stream URL",
        ["msg.streamHostBody"] = "URL ini tidak ada di daftar host streaming yang dikenal. Tetap buka dialog stream?",
        ["msg.settingsTitle"] = "Pengaturan",
        ["msg.noFolder"] = "Pilih folder unduhan.",
        ["msg.badFolder"] = "Folder itu tidak bisa dipakai:\n{0}",
        ["msg.startupFail"] = "Tidak bisa memperbarui startup:\n{0}",
        ["msg.browserFailTitle"] = "Integrasi browser",
        ["msg.browserFail"] = "Tidak bisa membuka {0}:\n{1}",
        ["msg.aboutTitle"] = "Tentang",
        ["msg.notInstalled"] = "tidak terpasang",
        // Self-update
        ["upd.title"] = "Cek pembaruan",
        ["upd.url"] = "URL manifest pembaruan (JSON generik atau GitHub Releases API)",
        ["upd.check"] = "Cek",
        ["upd.checking"] = "Memeriksa...",
        ["upd.current"] = "Versi sekarang: {0}",
        ["upd.available"] = "Versi {0} tersedia (sekarang {1}).",
        ["upd.latest"] = "Sudah versi terbaru ({0}).",
        ["upd.hint"] = "Contoh: https://raw.githubusercontent.com/ifredrix/DownloadManager/main/update/latest.json",
        ["upd.downloadRun"] = "Unduh & Jalankan",
        ["upd.saved"] = "Tersimpan: {0}",
        ["upd.runNow"] = "Pembaruan terunduh. Jalankan sekarang? (App akan keluar.)\n{0}",
        // Settings dialog
        ["set.title"] = "Pengaturan",
        ["set.folder"] = "Folder unduhan",
        ["set.concurrent"] = "Unduhan bersamaan",
        ["set.connections"] = "Koneksi per unduhan",
        ["set.speed"] = "Batas kecepatan (KB/s)",
        ["set.speedHint"] = "0 = tanpa batas",
        ["set.clipboard"] = "Awasi clipboard dan tambah tautan otomatis",
        ["set.autostartDl"] = "Langsung mulai unduhan",
        ["set.notify"] = "Beri tahu saat unduhan selesai",
        ["set.schedStart"] = "Mulai antrean jam",
        ["set.schedStop"] = "Jeda semua jam",
        ["set.afterDone"] = "Saat semua unduhan selesai",
        ["set.skin"] = "Skin",
        ["set.accent"] = "Aksen",
        ["set.customToolbar"] = "Kustomisasi toolbar...",
        ["set.routeTor"] = "Lewatkan semua via Tor",
        ["set.torSetup"] = "Setelan Tor...",
        ["set.startWindows"] = "Jalan saat Windows start",
        ["set.confirmDl"] = "Konfirmasi unduhan",
        ["set.none"] = "Tidak ada",
        ["set.shutdown"] = "Matikan",
        ["set.sleep"] = "Tidur",
        ["set.hibernate"] = "Hibernasi",
        // Grab / spider
        ["grab.title"] = "Tautan ditemukan di clipboard",
        ["grab.hint"] = "Centang tautan yang mau diunduh:",
        ["grab.selectNone"] = "Pilih tidak ada",
        ["grab.selectAll"] = "Pilih semua",
        ["grab.download"] = "Unduh",
        ["spider.title"] = "Ambil tautan dari halaman",
        ["spider.fetch"] = "Ambil",
        ["spider.depth0"] = "Halaman ini saja",
        ["spider.depth1"] = "Halaman ini + 1 level (situs sama)",
        ["spider.filesOnly"] = "Hanya berkas (lewati tautan halaman)",
        ["spider.idle"] = "Diam",
        ["spider.needUrl"] = "Isi alamat halaman dulu.",
        ["spider.fetching"] = "Mengambil...",
        ["spider.cancelled"] = "Dibatalkan.",
        // Stream dialog
        ["stream.title"] = "Tangkap stream (yt-dlp)",
        ["stream.list"] = "Daftar format",
        ["stream.download"] = "Unduh",
        ["stream.openFolder"] = "Buka folder",
        ["stream.getTool"] = "Ambil yt-dlp",
        ["stream.detecting"] = "yt-dlp: mendeteksi...",
        ["stream.notFound"] = "yt-dlp: tidak ketemu - tekan Ambil yt-dlp untuk mengunduh otomatis",
        ["stream.enumerating"] = "Mendaftar format...",
        ["stream.starting"] = "Menjalankan yt-dlp...",
        ["stream.fetching"] = "Mengunduh yt-dlp... {0:F0}%",
        ["stream.toolReady"] = "yt-dlp siap.",
        ["stream.checkFfmpeg"] = "Memeriksa ffmpeg (gabung / remux TS)...",
        // Tor dialog
        ["tor.title"] = "Setelan Tor",
        ["tor.mode"] = "Koneksi Tor",
        ["tor.off"] = "Mati - tanpa Tor",
        ["tor.external"] = "Eksternal - pakai Tor yang jalan",
        ["tor.managed"] = "Bawaan aplikasi ifredrix",
        ["tor.endpoint"] = "SOCKS host:port",
        ["tor.exe"] = "tor.exe (bawaan)",
        ["tor.exePlaceholder"] = "(kosongkan = pakai Tor bawaan aplikasi)",
        ["tor.find"] = "Cari",
        ["tor.routeAll"] = "Lewatkan semua unduhan HTTP via Tor",
        ["tor.hint"] = "Alamat .onion selalu pakai Tor bila koneksi tersedia.\r\nTor Browser = port 9150 saat terbuka; expert bundle = 9050.",
        ["tor.test"] = "Uji",
        ["tor.notFound"] = "Status: tor.exe tidak ketemu.",
        ["tor.exeFound"] = "Status: tor.exe ketemu.",
        ["tor.checking"] = "Status: memeriksa torproject.org...",
        ["tor.startingPct"] = "Status: memulai Tor... {0}% - sirkuit belum siap.",
        ["tor.checkingCircuit"] = "Status: {0}:{1} menjawab, membuktikan sirkuit Tor asli...",
        ["tor.noCircuit"] = "Status: {0}:{1} menjawab tapi belum ada sirkuit Tor yang bisa dipakai (masih bootstrap). Coba lagi sebentar.",
        ["tor.torReady"] = "Status: terkoneksi ke jaringan Tor (exit {0}) - siap dipakai mengunduh via Tor.",
        ["tor.noUpdate"] = "Status: Tor bawaan v{0} sudah terbaru.",
        ["tor.updateAvail"] = "Status: terpasang v{0}, tersedia v{1} (terverifikasi SHA256). Tekan Unduh.",
        ["tor.updateAvailNew"] = "Status: tersedia v{0} (terverifikasi SHA256, situs resmi saja).",
        ["tor.downloading"] = "Status: mengunduh Tor... {0:F0}%",
        ["tor.installed"] = "Status: terpasang -> {0}",
        ["tor.externalKeepsRunning"] = "Paket siap - mode Eksternal tetap memakai Tor yang sedang jalan. Pilih Terkelola + OK untuk menjalankan versi ini.",
        ["tor.checkUpdate"] = "Cek pembaruan",
        ["tor.download"] = "Unduh & pasang v{0}",
        ["tor.bundledNone"] = "Tor bawaan: tidak ada (pakai salinan Tor Browser atau PATH)",
        ["tor.bundledUnknown"] = "Tor bawaan: tidak diketahui",
        ["tor.reachable"] = "Status: Tor terjangkau di {0}:{1}.",
        ["tor.unreachable"] = "Status: tidak ada yang listen di {0}:{1}.",
        ["tor.off"] = "Tor mati",
        ["tor.tipOff"] = "Tor dimatikan (Setelan Tor di Pengaturan)",
        ["tor.tipBoot"] = "Tor sedang bootstrap...",
        ["tor.tipOk"] = "Tor terjangkau di {0}:{1}",
        ["tor.tipMissing"] = "Tor tidak terdeteksi - unduhan .onion butuh Tor Browser atau expert bundle",
        // Proxy dialog
        ["proxy.title"] = "Setelan Proksi",
        ["proxy.mode"] = "Mode proksi",
        ["proxy.host"] = "Host : port",
        ["proxy.user"] = "Nama pengguna",
        ["proxy.pass"] = "Kata sandi",
        ["proxy.hint"] = "Login situs: taruh di tautannya,\r\nhttp://user:pass@host/file (dikirim sebagai Basic auth).",
        ["proxy.test"] = "Uji",
        ["proxy.nothing"] = "Status: tidak ada yang diuji untuk mode {0}.",
        ["proxy.reachable"] = "Status: proksi terjangkau.",
        ["proxy.unreachable"] = "Status: proksi tidak terjangkau.",
        // Toolbar editor
        ["tb.title"] = "Kustomisasi toolbar",
        ["tb.hint"] = "Centang tombol untuk tampil, atur urutan dengan Atas / Bawah:",
        ["tb.up"] = "Atas",
        ["tb.down"] = "Bawah",
        // Browser integration
        ["br.title"] = "Integrasi browser",
        ["br.hint"] = "Pasang ekstensi di tiap browser yang dipakai. Semua browser memakai server capture yang sama, tanpa restart.",
        ["br.installed"] = "terpasang",
        ["br.notFound"] = "tidak ketemu",
        ["br.connected"] = "tersambung ✓",
        ["br.notSeen"] = "tidak terlihat ✗",
        ["br.install"] = "Pasang...",
        ["br.steps"] = "Folder ekstensi disalin ke clipboard.\n\n{0}",
        ["br.stepsFx"] = "1. Halaman debugging Firefox terbuka.\n2. Klik \"Load Temporary Add-on…\".\n3. Pilih manifest.json di folder ini (sudah disalin):\n{0}",
        ["br.stepsCr"] = "1. Halaman extensions terbuka. Nyalakan Developer mode.\n2. Klik \"Load unpacked\".\n3. Pilih folder ini (sudah disalin):\n{0}",
        // Category folders
        ["cf.title"] = "Folder kategori",
        ["cf.hint"] = "Tempat tiap jenis unduhan disimpan. Kosong = folder unduhan utama.",
        ["cf.category"] = "Kategori",
        ["cf.folder"] = "Folder",
        ["cf.main"] = "(folder utama)",
        ["cf.clear"] = "Kosongkan",
        ["cf.resetAll"] = "Reset semua",
        // Speed limit
        ["sl.hint"] = "0 = pakai batas global.",
        ["sl.limitTo"] = "Batasi unduhan ini hingga (KB/s):",
        ["sl.title"] = "Batas kecepatan",
        // Batch add
        ["batch.title"] = "Tambah batch",
        ["batch.hint"] = "Satu tautan per baris (atau path .torrent). Masing-masing dirute otomatis.",
        ["batch.add"] = "Tambah semua",
        ["batch.found"] = "{0} tautan ditemukan.",
        ["batch.done"] = "{0} tautan dikirim ke antrean.",
        // URL exclusions
        ["ex.title"] = "Pengecualian URL",
        ["ex.hint"] = "Satu pola wildcard per baris (* dan ?). # untuk komentar.\r\nTautan cocok dilewati clipboard dan browser capture.",
        ["ex.test"] = "Uji URL:",
        ["ex.check"] = "Cek",
        ["ex.excluded"] = "Dikecualikan (akan dilewati).",
        ["ex.allowed"] = "Diizinkan (akan ditangkap).",
        // Properties
        ["pr.title"] = "Properti unduhan",
        ["pr.file"] = "Nama berkas",
        ["pr.url"] = "URL",
        ["pr.saveAs"] = "Simpan sebagai",
        ["pr.type"] = "Jenis",
        ["pr.category"] = "Kategori",
        ["pr.status"] = "Status",
        ["pr.size"] = "Ukuran",
        ["pr.downloaded"] = "Terunduh",
        ["pr.speed"] = "Kecepatan",
        ["pr.limit"] = "Batas kecepatan",
        ["pr.eta"] = "ETA",
        ["pr.created"] = "Dibuat",
        ["pr.completed"] = "Selesai",
        ["pr.tor"] = "Via Tor",
        ["pr.resume"] = "Dukungan lanjut",
        ["pr.error"] = "Galat",
        ["pr.copyUrl"] = "Salin URL",
        ["pr.yes"] = "Ya",
        ["pr.no"] = "Tidak",
        ["pr.none"] = "-",
        ["pr.unknown"] = "Tidak diketahui",
        ["pr.downUp"] = "{0} unduh / {1} unggah",
        ["pr.of"] = "{0} dari {1} ({2:0.0}%)",
        ["pr.limitThis"] = "{0:F0} KB/s (unduhan ini)",
        ["pr.limitGlobal"] = "Global",
        // New download dialog
        ["dl.title"] = "Unduhan baru",
        ["dl.url"] = "Alamat (URL)",
        ["dl.file"] = "Nama berkas",
        ["dl.saveIn"] = "Simpan di",
        ["dl.info"] = "Ukuran: {0}   Resume: {1}",
        ["dl.needName"] = "Isi nama berkas.",
        // Progress window
        ["prog.statusTab"] = "Status unduhan",
        ["prog.speedTab"] = "Pembatas Kecepatan",
        ["prog.optionsTab"] = "Opsi saat selesai",
        ["prog.status"] = "Status:",
        ["prog.size"] = "Ukuran berkas",
        ["prog.downloaded"] = "Diunduh",
        ["prog.rate"] = "Tingkat transfer",
        ["prog.eta"] = "Waktu tersisa",
        ["prog.resume"] = "Kemampuan resume",
        ["prog.hide"] = "<< Sembunyikan detail",
        ["prog.show"] = "Tampilkan detail >>",
        ["prog.pause"] = "Jeda",
        ["prog.resume"] = "Lanjutkan",
        ["prog.cancel"] = "Batal",
        ["prog.progress"] = "Progres",
        ["prog.detailCaption"] = "Progres posisi mulai dan unduh berdasarkan koneksi",
        ["prog.colN"] = "N.",
        ["prog.colDownloaded"] = "Diunduh",
        ["prog.colInfo"] = "Info",
        ["prog.receiving"] = "Menerima data...",
        ["prog.done"] = "Selesai",
        ["prog.waiting"] = "Menunggu",
        ["prog.torrentConn"] = "{0} koneksi",
        ["prog.limitLabel"] = "Batasi unduhan ini hingga (KB/s):",
        ["prog.limitCurrent"] = "Batas aktif: {0}",
        ["prog.apply"] = "Terapkan",
        ["prog.closeOnDone"] = "Tutup jendela ini saat selesai",
        ["prog.openFolderOnDone"] = "Buka folder berkas saat selesai",
    };
}
